import React from 'react';
import { Check } from 'lucide-react';

const Partnership: React.FC = () => {
  return (
    <section id="partnership" className="py-20 sm:py-32 bg-brand-panel border-y border-white/5 relative overflow-hidden">
      {/* Background Decor */}
      <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-brand-purple/5 rounded-full blur-[120px] pointer-events-none"></div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-3xl mx-auto mb-12 sm:mb-20 px-2">
          <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold text-white mb-4 sm:mb-6">
            Tired of Paying for <br />
            <span className="text-brand-purple">Results You Never See?</span>
          </h2>
          <p className="text-base sm:text-lg text-slate-400">
            We've heard the horror stories: agencies that disappear after the invoice, consultants who deliver PDFs instead of outcomes. Our model is different—we only win when you win.
          </p>
        </div>

        <div className="grid gap-6 sm:gap-8 lg:grid-cols-2 items-stretch max-w-5xl mx-auto">

          {/* Phase 1 */}
          <div className="bg-white/5 border border-white/10 rounded-2xl sm:rounded-3xl p-6 sm:p-10 hover:bg-white/[0.07] transition-colors relative group">
            <div className="absolute top-6 right-6 sm:top-8 sm:right-8 text-white/5 group-hover:text-white/10 transition-colors font-black text-5xl sm:text-7xl select-none">01</div>
            <h3 className="text-xl sm:text-2xl font-bold text-white mb-3 sm:mb-4 relative z-10">Phase 1: Setup & Systems</h3>
            <p className="text-sm sm:text-base text-slate-400 mb-6 sm:mb-8 leading-relaxed relative z-10">
              A one-time setup fee to cover the Forensic Audit and infrastructure build-out. We build the engine before we turn the key.
            </p>
            <ul className="space-y-4 relative z-10">
              <li className="flex items-center gap-3 text-sm text-slate-300">
                <div className="bg-brand-purple/20 p-1.5 rounded text-brand-purple"><Check size={16} /></div>
                Forensic Audit & Strategy Roadmap
              </li>
              <li className="flex items-center gap-3 text-sm text-slate-300">
                <div className="bg-brand-purple/20 p-1.5 rounded text-brand-purple"><Check size={16} /></div>
                Custom Infrastructure Implementation
              </li>
              <li className="flex items-center gap-3 text-sm text-slate-300">
                <div className="bg-brand-purple/20 p-1.5 rounded text-brand-purple"><Check size={16} /></div>
                Workflow & Protocol Optimization
              </li>
            </ul>
          </div>

          {/* Phase 2 */}
          <div className="bg-gradient-to-br from-brand-purple/10 to-transparent border border-brand-purple/30 rounded-2xl sm:rounded-3xl p-6 sm:p-10 relative group">
            <div className="absolute top-6 right-6 sm:top-8 sm:right-8 text-brand-purple/10 group-hover:text-brand-purple/20 transition-colors font-black text-5xl sm:text-7xl select-none">02</div>
            <h3 className="text-xl sm:text-2xl font-bold text-white mb-3 sm:mb-4 relative z-10">Phase 2: Performance Stake</h3>
            <p className="text-sm sm:text-base text-slate-400 mb-6 sm:mb-8 leading-relaxed relative z-10">
              We only take a percentage of the <strong className="text-white">NEW</strong> net profit generated by our systems. If we don't add profit to your business, we don't get paid.
            </p>
            <ul className="space-y-4 relative z-10">
              <li className="flex items-center gap-3 text-sm text-slate-300">
                <div className="bg-brand-purple/20 p-1.5 rounded text-brand-purple"><Check size={16} /></div>
                Zero Monthly Retainers
              </li>
              <li className="flex items-center gap-3 text-sm text-slate-300">
                <div className="bg-brand-purple/20 p-1.5 rounded text-brand-purple"><Check size={16} /></div>
                Profit-Share on New Revenue Only
              </li>
              <li className="flex items-center gap-3 text-sm text-slate-300">
                <div className="bg-brand-purple/20 p-1.5 rounded text-brand-purple"><Check size={16} /></div>
                Quarterly Strategy Alignment
              </li>
            </ul>
          </div>

        </div>
        {/* Guarantee bar removed */}
      </div>
    </section>
  );
};

export default Partnership;